### PR TITLE
fix: update subscription component name and styles

### LINKED ISSUE #342: [BUG] Decrease the top padding in subscribe section in mobile view
### Describe the bug.

The top padding in the subscribe section is way too much for the mobile view.

### Expected behavior

The padding should be less and more  symmetrical

### Screenshots

Screenshot from 2024-07-06 14-45-44

### How to Reproduce

1. Open the conference website in mobile view.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

### PR DESCRIPTION
**Pull request by ALIPHATICHYD**
The subscription component name was misspelled as "Subcription". This commit fixes the typo and updates the component styles to improve the layout on different screen sizes.

**Description**

- ...
- ...
- ...

**Related issue(s)**

Resolves #342

### CODE REVIEW

**Review by ashmit-coder — APPROVED** [review]
LGTM!

**Comment by ashmit-coder** [comment]
@ALIPHATICHYD please mention the issue in your pr description

**Comment by ALIPHATICHYD** [comment]
> @ALIPHATICHYD please mention the issue in your pr description

Just did that now 
Thank you very much

File: components/Form/subscription.js [hunk 1]
```diff
@@ -1,25 +1,25 @@
...
-					type='submit'
-					className='w-full md:w-[200px] mt-8 px-10' 
-				>
-					Subscribe
-				</Button>
+						type='submit'
+						className='w-full md:w-[200px] mt-8 px-10'
+					>
+						Subscribe
+					</Button>
```
Comment (AnimeshKumar923) [inline components/Form/subscription.js:17]: @ALIPHATICHYD @ashmit-coder why so much whitespace though? :thinking:

Comment (ALIPHATICHYD) [reply components/Form/subscription.js:17]: I'm so sorry about that, I'd make sure I adjust that 
I didn't know it will come out that way.

Comment (ashmit-coder) [reply components/Form/subscription.js:17]: True, please look into it.

**Comment by AceTheCreator** [comment]
@ashmit-coder, @AnimeshKumar923 is this pr up for merge?

**Review by AnimeshKumar923 — APPROVED** [review]
LGTM! ✅

cc: @AceTheCreator

File: components/Form/subscription.js (hunk 1 above)
Comment (AnimeshKumar923) [reply components/Form/subscription.js]: > I'm so sorry about that, I'd make sure I adjust that I didn't know it will come out that way.

No problem. It happens sometimes due to auto-formatting extensions running wild. Thanks for the PR @ALIPHATICHYD

**Comment by AnimeshKumar923** [comment]
Just a small nitpick about your PR description @ALIPHATICHYD 

---

Your PR description currently looks like this :point_down: 
```
Resolves #342 
The subscription component name was misspelled as "Subcription". This commit fixes the typo and updates the component styles to improve the layout on different screen sizes.

Description

    ...
    ...
    ...

Related issue(s)
```

While it should ideally have been like this :point_down: 
```
Description

The subscription component name was misspelled as "Subcription". This commit fixes the typo and updates the component styles to improve the layout on different screen sizes.

Related issue(s)
Resolves #342 
```
---
You can remove those initial placeholders and put your own description and issue number under the appropriate sections when you open a PR. Try it next time you put up a PR :wink:

**Comment by ALIPHATICHYD** [comment]
> Just a small nitpick about your PR description @ALIPHATICHYD
> 
> Your PR description currently looks like this 👇
> 
> ```
> Resolves #342 
> The subscription component name was misspelled as "Subcription". This commit fixes the typo and updates the component styles to improve the layout on different screen sizes.
> 
> Description
> 
>     ...
>     ...
>     ...
> 
> Related issue(s)
> ```
> 
> While it should ideally have been like this 👇
> 
> ```
> Description
> 
> The subscription component name was misspelled as "Subcription". This commit fixes the typo and updates the component styles to improve the layout on different screen sizes.
> 
> Related issue(s)
> Resolves #342 
> ```
> 
> You can remove those initial placeholders and put your own description and issue number under the appropriate sections when you open a PR. Try it next time you put up a PR 😉

Noted 
Just did that now

**Review by AceTheCreator — APPROVED** [review]
Thanks for the review @AnimeshKumar923. LGTM!

**Comment by AceTheCreator** [comment]
> Thanks for the review @AnimeshKumar923. LGTM!

@ALIPHATICHYD I noticed there are changes in package.lock, can you get rid of that?

**Comment by ALIPHATICHYD** [comment]
> > Thanks for the review @AnimeshKumar923. LGTM!
> 
> @ALIPHATICHYD I noticed there are changes in package.lock, can you get rid of that?

Done ☑️

**Comment by AceTheCreator** [comment]
@ALIPHATICHYD there seems to be an error, your changes are not rendering :/

**Comment by ALIPHATICHYD** [comment]
I will try resolving it from my end.

File: components/Form/subscription.js [hunk 2]
```diff
@@ -1,25 +1,19 @@
...
+				<Button type='submit' className='w-full md:w-[200px] mt-8 px-10'>
 					Subscribe
 				</Button>
-
 				</a>
 			</div>
 		</div>
 	);
 }
-
```
Comment (ashmit-coder) [inline components/Form/subscription.js:24]: Hey @ALIPHATICHYD I guess you have not exported the new formed 'Subscription' Component, thats why the error

Comment (AceTheCreator) [reply components/Form/subscription.js:24]: cc @ALIPHATICHYD

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Comment by oluseguncodess** [comment]
Nice one @ALIPHATICHYD !
