### PR TITLE
fix: added venue link navigation

### LINKED ISSUE #269: Make venue card clickable
The venue cards on the website are currently unclickable, but it should take you to the venue page when clicked.

### PR DESCRIPTION
**Pull request by shauryag2002**
fixes #269 

**Description**

- Added Link navigation when click on particular venue tab

**Video of Changes**

https://github.com/asyncapi/conference-website/assets/77102885/4b998d72-1dee-41a0-850c-0dfee1cc34fd

### CODE REVIEW

**Comment by AceTheCreator** [comment]
Awesome!!! @shauryag2002

**Comment by AceTheCreator** [comment]
But the Pin icon is not linking to google map anymore, please fix that and we should be cool to go :)

**Comment by shauryag2002** [comment]
> But the Pin icon is not linking to google map anymore, please fix that and we should be cool to go :)

@AceTheCreator Done!

File: components/Venue/venue.js [hunk 1]
```diff
@@ -1,30 +1,34 @@
...
+				className='relative w-[300px] h-[400px] sm:w-[250px] sm:h-[350px] card-bg bg-[image:var(--image-url)] flex items-center justify-center p-4 cursor-pointer'>
 				<div className='flex justify-between flex-col w-full h-full'>
 					<div className='flex justify-between items-center'>
 						<div><div className={`border text-white text-md rounded-lg p-1 text-center mt-2 ${city.cfp ? 'block': 'hidden' }`}>cfp is open</div></div>
-						<a href={city.map} target='_blank' className='w-8 h-8 bg-white rounded-xl flex items-center justify-center' rel="noreferrer">
-						<img src='/img/mapIcon.svg' className='w-6' />
-						</a>
+						<button onClick={(e) => {
+							e.preventDefault()
+							window.open(city.map, '_blank')
```
Comment (AceTheCreator) [inline components/Venue/venue.js:15]: Can you make the window.open function look like this,` (city.map,'_blank','noopener')`? cuz of vulnerability issue

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
Left you a review :)

File: components/Venue/venue.js [hunk 2]
```diff
@@ -1,30 +1,34 @@
...
 	return (
-		<div>
-			<div style={{'--image-url': `url(${city.img})`}} 
-			className='relative w-[300px] h-[400px] sm:w-[250px] sm:h-[350px] card-bg bg-[image:var(--image-url)] flex items-center justify-center p-4 cursor-pointer'>
+		<Link href={`/venue/${city.name}`}>
+			<div style={{'--image-url': `url(${city.img})`}}
+				className='relative w-[300px] h-[400px] sm:w-[250px] sm:h-[350px] card-bg bg-[image:var(--image-url)] flex items-center justify-center p-4 cursor-pointer'>
 				<div className='flex justify-between flex-col w-full h-full'>
 					<div className='flex justify-between items-center'>
 						<div><div className={`border text-white text-md rounded-lg p-1 text-center mt-2 ${city.cfp ? 'block': 'hidden' }`}>cfp is open</div></div>
```
Comment (RamGoel) [inline components/Venue/venue.js:12]: suggestion: instead of setting the classnames as `block` or `hidden`, we can render/remove the whole div from DOM if `city.cfp` exists/not exists.

Why? - If at some point, the Venue component is used 100 times in website, then we'll be saving 100 nodes from DOM.

Changes required-
- Removing `mt-2` from cfp div and adding it to parent. to keep everything aligned.
- setting ml-auto on map link to make sure it stays on right side even if cfp is not available.

@AceTheCreator you can suggest if we should do this or not.

Comment (AceTheCreator) [reply components/Venue/venue.js]: I agree with you @RamGoel 👍🏾

File: components/Venue/venue.js [hunk 3]
```diff
@@ -8,8 +8,8 @@ function Venue({ className, city }) {
 			<div style={{'--image-url': `url(${city.img})`}}
 				className='relative w-[300px] h-[400px] sm:w-[250px] sm:h-[350px] card-bg bg-[image:var(--image-url)] flex items-center justify-center p-4 cursor-pointer'>
 				<div className='flex justify-between flex-col w-full h-full'>
-					<div className='flex justify-between items-center'>
-						<div><div className={`border text-white text-md rounded-lg p-1 text-center mt-2 ${city.cfp ? 'block': 'hidden' }`}>cfp is open</div></div>
+					<div className={`flex ${city.cfp ? 'justify-between' : 'justify-end'} items-center`}>
```
Comment (RamGoel) [inline components/Venue/venue.js:11]: @shauryag2002 it is not required, just add `ml-auto` to map link, and we'll be good to go.

File: components/Venue/venue.js [hunk 4]
```diff
@@ -8,8 +8,8 @@ function Venue({ className, city }) {
...
+						{city.cfp? <div><div className='border text-white text-md rounded-lg p-1 text-center mt-2'>cfp is open</div></div> :null}
```
Comment (RamGoel) [inline components/Venue/venue.js:12]: Remove extra div wrapping the `cfp is open` div.

File: components/Venue/venue.js (hunk 3 above)
Comment (shauryag2002) [reply components/Venue/venue.js]: Done, PTAL!

File: components/Venue/venue.js (hunk 4 above)
Comment (shauryag2002) [reply components/Venue/venue.js]: Done, PTAL!

**Review by RamGoel — APPROVED** [review]

File: components/Venue/venue.js (hunk 4 above)
Comment (RamGoel) [reply components/Venue/venue.js]: LGTM 🚀

**Comment by thulieblack** [comment]
@AceTheCreator @Mayaleeeee please take a look

**Review by AceTheCreator — APPROVED** [review]
LGTM!!!

**Comment by RamGoel** [comment]
@Mayaleeeee I am not the actual author of this PR. But can you put here, what hover state you want to add here. @shauryag2002 would be the ideal person to pickup this. 

If not, @shauryag2002 let me know. I'll do it in some time.
