### PR TITLE
fix: add Links to sponsors Images

### LINKED ISSUE #446: [FEAT]Make Sponsor Logo Images Clickable with Links to Sponsor Websites
### Why do we need this improvement?

- Enhanced Sponsor Visibility: Increases value for sponsors by directing traffic to their sites.
- Improved User Experience: Aligns with standard web navigation, making the site more intuitive.

### How will this change help?

 Increases visits to sponsor websites directly from our site.

### Screenshots

_No response_

### How could it be implemented/designed?

add Link to each image with there corresponding website

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by anmolyadav-dev**
**Description**
Added sponsor's website links to their respective logo

**Related Issue**
Fixes #446

### CODE REVIEW

File: pages/index.js [hunk 1]
```diff
@@ -185,7 +185,7 @@ export default function Home() {
 			</div>
 			</div>
 			<div id='sponsors' className='mt-20'>
-				<Sponsors imgs={['/img/apidays.png']} />
+				<Sponsors imgs={[{image:'/img/apidays.png',sponsorUrl:"https://www.apidays.global/"}]} />
```
Comment (AceTheCreator) [inline pages/index.js:188]: Can you extend this prop to include the remaining sponsors?

**Review by AceTheCreator — COMMENTED** [review]
Left you a review

File: pages/index.js (hunk 1 above)
Comment (anmolyadav-dev) [reply pages/index.js:188]: Hi @AceTheCreator,

Should I create a separate prop for the financial sponsors instead of keeping them hardcoded as they are now, or anything else?

Comment (anmolyadav-dev) [reply pages/index.js]: Hi @AceTheCreator,

I've updated the component to extend the imgs prop, now including both financial and event sponsors. Let me know if there's anything specific you'd like me to adjust further!

**Review by AceTheCreator — APPROVED** [review]
LGTM!
